Changed the page for listed items visually using css | Added list of …
GROUP-THR3E/AJExchange pull request #78
Opened 2022-12-12 17:31 UTC by evenchowder

Not related to specific issue - Improved css design of item page

2022-12-12 17:35 UTC, evenchowder commented
Note: The 2 Grid column changes in style.css were accidental you can revert those 2 it doesn't affect the page

2022-12-12 18:12 UTC, An-Owlbear requested changes
Looks great! Just needs a couple changes to make the code a little more readable

2022-12-12 18:12 UTC, An-Owlbear commented on public/css/style.css
> +
To clarify, what does flex do for this button, i can't see it doing anything differently from block.

2022-12-12 18:12 UTC, An-Owlbear commented on src/Views/listings/view.phtml
> +            <h1> <?=htmlspecialchars($listing->getListingName()) ?></h1>
Remove the whitespace here and at the start of other tags with similar whitespace

2022-12-12 18:12 UTC, An-Owlbear commented on src/Views/listings/view.phtml
> +            <ul style="list-style-type:none; padding: 0;" class="tag-list home-list-design">
Use list-unstyled bootstrap class instead of style tag

2022-12-12 20:29 UTC, An-Owlbear requested changes
Thanks! There's just a couple more things that need doing before merging

2022-12-12 20:29 UTC, An-Owlbear commented on src/Views/listings/view.phtml
>          <button type="submit" class="btn btn-primary btn-align w-100 mt-4">Submit</button><br>
The \<br\> should be replaced with a bottom margin. my-4 could be used here

2022-12-12 20:29 UTC, An-Owlbear commented on public/css/style.css
>  .btn-align {
This class is now not needed, as justify-content has no effect unless display is set to flex

2022-12-12 20:29 UTC, An-Owlbear commented on src/Views/listings/view.phtml
> +            <h1><?=htmlspecialchars($listing->getListingName()) ?></h1>
Sorry I didn't say earlier, but for consistency all the php tags should have a space at the start and end

2022-12-13 00:55 UTC, evenchowder commented
To be clear for php syntax did you mean spaces after the <?= or before as I thought you meant before

2022-12-13 09:19 UTC, An-Owlbear commented
yeah after the <?=, like <?= $var ?> instead of <?=$var?>

2022-12-13 09:32 UTC, An-Owlbear approved these changes

2022-12-13 10:32 UTC, merged